# Generated by Django 4.2.4 on 2023-08-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorry',
            new_name='category',
        ),
    ]
